/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISeaportContract,
  ISeaportContractInterface,
} from "../../../../contracts/vrf/ISeaportInterface.sol/ISeaportContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "numerator",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "denominator",
        type: "uint256",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISeaportContract__factory {
  static readonly abi = _abi;
  static createInterface(): ISeaportContractInterface {
    return new utils.Interface(_abi) as ISeaportContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISeaportContract {
    return new Contract(address, _abi, signerOrProvider) as ISeaportContract;
  }
}
