/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CreatorFeeEngineInterface,
  CreatorFeeEngineInterfaceInterface,
} from "../../../../../../contracts/helpers/order-validator/lib/SeaportValidatorHelper.sol/CreatorFeeEngineInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "getRoyaltyView",
    outputs: [
      {
        internalType: "address payable[]",
        name: "recipients",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class CreatorFeeEngineInterface__factory {
  static readonly abi = _abi;
  static createInterface(): CreatorFeeEngineInterfaceInterface {
    return new utils.Interface(_abi) as CreatorFeeEngineInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CreatorFeeEngineInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as CreatorFeeEngineInterface;
  }
}
