/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVRFInterface__factory } from "./IVRFInterface__factory";
export { TestVRF__factory } from "./TestVRF__factory";
